// <auto-generated />
using System;
using ART122.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ART122.Migrations
{
    [DbContext(typeof(ImpotDbContext))]
    [Migration("20260521174810_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("ART122.Data.Impot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BP")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PR")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedevableInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YearImpot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RedevableInfoId");

                    b.HasIndex("RoleNumber");

                    b.ToTable("Impots");
                });

            modelBuilder.Entity("ART122.Data.NatureImpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NatureImpots");
                });

            modelBuilder.Entity("ART122.Data.RedevableInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Article")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etablissement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NIF")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BP");

                    b.ToTable("Redevables");
                });

            modelBuilder.Entity("ImpotNature", b =>
                {
                    b.Property<int>("ImpotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NatureImpotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImpotId", "NatureImpotId");

                    b.HasIndex("NatureImpotId");

                    b.ToTable("ImpotNature", (string)null);
                });

            modelBuilder.Entity("ART122.Data.Impot", b =>
                {
                    b.HasOne("ART122.Data.RedevableInfo", "RedevableInfo")
                        .WithMany("Impots")
                        .HasForeignKey("RedevableInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedevableInfo");
                });

            modelBuilder.Entity("ImpotNature", b =>
                {
                    b.HasOne("ART122.Data.Impot", null)
                        .WithMany()
                        .HasForeignKey("ImpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ART122.Data.NatureImpot", null)
                        .WithMany()
                        .HasForeignKey("NatureImpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ART122.Data.RedevableInfo", b =>
                {
                    b.Navigation("Impots");
                });
#pragma warning restore 612, 618
        }
    }
}
