// <auto-generated />
using System;
using ART122.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ART122.Migrations
{
    [DbContext(typeof(ImpotDbContext))]
    partial class ImpotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("ART122.Data.Declaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlaAqsat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DafaaWahida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Droit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantRestant")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PR")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedevableInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RedevableInfoId");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("ART122.Data.Impot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BP")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Droit")
                        .HasColumnType("TEXT");

                    b.Property<int>("NatureImpotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PR")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedevableInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearImpot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NatureImpotId");

                    b.HasIndex("RedevableInfoId");

                    b.ToTable("Impots");
                });

            modelBuilder.Entity("ART122.Data.NatureImpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NatureImpots");
                });

            modelBuilder.Entity("ART122.Data.RedevableInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Article")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etablissement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilsDe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NIF")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Article")
                        .IsUnique();

                    b.HasIndex("BP")
                        .IsUnique();

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.ToTable("Redevables");
                });

            modelBuilder.Entity("ART122.Data.Declaration", b =>
                {
                    b.HasOne("ART122.Data.RedevableInfo", "RedevableInfo")
                        .WithMany()
                        .HasForeignKey("RedevableInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedevableInfo");
                });

            modelBuilder.Entity("ART122.Data.Impot", b =>
                {
                    b.HasOne("ART122.Data.NatureImpot", "NatureImpot")
                        .WithMany()
                        .HasForeignKey("NatureImpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ART122.Data.RedevableInfo", "RedevableInfo")
                        .WithMany("Impots")
                        .HasForeignKey("RedevableInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NatureImpot");

                    b.Navigation("RedevableInfo");
                });

            modelBuilder.Entity("ART122.Data.RedevableInfo", b =>
                {
                    b.Navigation("Impots");
                });
#pragma warning restore 612, 618
        }
    }
}
